name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      # Main GitHub Metrics Profile Summary
      - name: Generate Profile Summary
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          base: header, activity, community, repositories

      # Most Used Languages
      - name: Generate Most Used Languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage

      # Repositories Overview
      - name: Generate Repositories Overview
        uses: lowlighter/metrics@latest
        with:
          filename: repos.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          plugin_repositories: yes
          plugin_repositories_affiliations: owner, collaborator

      # Contribution Calendar
      - name: Generate Contribution Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: iso-calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          plugin_iso_calendar: yes

      # Total Stars Earned
      - name: Generate Total Stars Earned
        uses: lowlighter/metrics@latest
        with:
          filename: stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          plugin_stars: yes
          plugin_stars_limit: 100

      # Total PRs & Issues
      - name: Generate Total PRs & Issues
        uses: lowlighter/metrics@latest
        with:
          filename: prs-issues.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          plugin_followup: yes
          plugin_followup_sections: prs, issues

      # Coding Activity (Commits Per Hour & Day)
      - name: Generate Coding Activity
        uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          plugin_habits: yes
          plugin_habits_days: yes
          plugin_habits_facts: yes

      # Lines of Code Written
      - name: Generate Lines of Code Written
        uses: lowlighter/metrics@latest
        with:
          filename: lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          plugin_lines: yes

      # Achievements & Badges
      - name: Generate Achievements & Badges
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          plugin_achievements: yes
          plugin_achievements_threshold: C

      # Activity Graph (Top Contributors)
      - name: Generate Activity Graph
        uses: lowlighter/metrics@latest
        with:
          filename: contributors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: klakshman318
          plugin_contributors: yes
