# Complete GitHub Snake Animation Setup

name: Generate Snake Animation

# Controls when the action will run
on:
  # Triggers the workflow on schedule (every 12 hours)
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches:
    - main
    - master

# A workflow run is made up of one or more jobs
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Generates the snake animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_empty=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39

      # Push the generated files to output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---

## Step 2: Setup Instructions

### 2.1 Create the workflow file
1. In your GitHub profile repository (klakshman318/klakshman318)
2. Create folder: `.github/workflows/`
3. Create file: `snake.yml` with the above content

### 2.2 Enable GitHub Actions
1. Go to your repository Settings
2. Navigate to Actions → General
3. Ensure "Allow all actions and reusable workflows" is selected
4. Save changes

### 2.3 Run the workflow manually (first time)
1. Go to Actions tab in your repository
2. Click on "Generate Snake Animation" workflow
3. Click "Run workflow" → "Run workflow"
4. Wait for completion (green checkmark)

### 2.4 Verify output branch creation
After successful run, you should see:
- New branch called "output"
- Generated SVG files in that branch

---

## Step 3: Add to README.md

### Option 1: Simple Snake (Light theme)
```markdown
## 🐍 Contribution Snake
![Snake animation](https://raw.githubusercontent.com/klakshman318/klakshman318/output/github-contribution-grid-snake.svg)
```

### Option 2: Dark Theme Snake
```markdown
## 🐍 Contribution Snake
![Snake animation](https://raw.githubusercontent.com/klakshman318/klakshman318/output/github-contribution-grid-snake-dark.svg)
```

### Option 3: Multiple Themes with Fallbacks
```markdown
## 🐍 Watch My Contributions Get Devoured!

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/klakshman318/klakshman318/output/github-contribution-grid-snake-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/klakshman318/klakshman318/output/github-contribution-grid-snake.svg">
  <img alt="github contribution grid snake animation" src="https://raw.githubusercontent.com/klakshman318/klakshman318/output/github-contribution-grid-snake.svg">
</picture>

### Alternative Ocean Theme
![Ocean Snake](https://raw.githubusercontent.com/klakshman318/klakshman318/output/ocean.svg)
```

### Option 4: Centered with Description
```markdown
<div align="center">

## 🐍 Snake Eating My Contributions

![Snake animation](https://raw.githubusercontent.com/klakshman318/klakshman318/output/github-contribution-grid-snake-dark.svg)

*The snake represents my coding journey - eating up all those green contribution squares!*

</div>
```

---

## Step 4: Customization Options

### Custom Colors & Themes
```yaml
# In the workflow file, modify the outputs section:
outputs: |
  dist/github-contribution-grid-snake.svg
  dist/github-contribution-grid-snake-dark.svg?palette=github-dark
  dist/custom-theme.svg?color_snake=#ff6b6b&color_dots=#ff8e53,#ff6b6b,#ee5a24,#e55039,#c23616
  dist/ocean-theme.svg?color_snake=#00d4aa&color_dots=#c0f7ed,#7fdbda,#39a0ca,#1e6091,#042f4a
  dist/forest-theme.svg?color_snake=#27ae60&color_dots=#d5f4e6,#80e27e,#4dd599,#26de81,#01a3a4
```

### Snake Animation Speed
```yaml
# Add animation options
dist/fast-snake.svg?animation_duration=0.6
dist/slow-snake.svg?animation_duration=2.0
```

---

## Step 5: Troubleshooting

### Common Issues:

1. **Snake not showing**
   - Wait 24 hours after first run
   - Check if Actions are enabled
   - Verify output branch exists

2. **Permission errors**
   - Go to Settings → Actions → General
   - Under "Workflow permissions" select "Read and write permissions"
   - Check "Allow GitHub Actions to create and approve pull requests"

3. **Workflow fails**
   - Check if repository name matches username
   - Ensure you have public contributions
   - Try running workflow manually

### Force Refresh
```markdown
<!-- Add timestamp to force refresh -->
![Snake animation](https://raw.githubusercontent.com/klakshman318/klakshman318/output/github-contribution-grid-snake.svg?t=<?php echo time(); ?>)
```

---

## Step 6: Advanced Configuration

### Multiple Snakes with Different Styles
```yaml
outputs: |
  dist/snake-light.svg?palette=github
  dist/snake-dark.svg?palette=github-dark  
  dist/snake-neon.svg?color_snake=#ff0080&color_dots=#ff0080,#ff4da6,#ff80cc,#ffb3e6,#ffffff
  dist/snake-matrix.svg?color_snake=#00ff00&color_dots=#001100,#003300,#00ff00,#66ff66,#ffffff
  dist/snake-fire.svg?color_snake=#ff4500&color_dots=#ffff00,#ff8c00,#ff4500,#dc143c,#8b0000
```

### Conditional Display
```markdown
<!-- Show different snakes based on theme -->
![Snake Light](https://raw.githubusercontent.com/klakshman318/klakshman318/output/snake-light.svg#gh-light-mode-only)
![Snake Dark](https://raw.githubusercontent.com/klakshman318/klakshman318/output/snake-dark.svg#gh-dark-mode-only)
```
